kubermaticOperator:
    image:
        tag: v2.19.2
dex:
    ingress:
        host: tn.creometry.com
    certIssuer:
        name: letsencrypt-prod
        kind: ClusterIssuer
    env:
        - name: KUBERNETES_POD_NAMESPACE
          value: oauth
    staticPasswords:
        - email: mghlaiel
          hash: ENC[AES256_GCM,data:UGeNS9HNsgGAKkXBp4M6GH8QOlv2TG+f86qH3pX4wQonDCIkIHSi5OhO2OSa4IK/FGlu/drlJoFOhXv1,iv:jpAZ76FYtwXz38Mmyc2SW/cHwSckE8KKwU0JuMA7UiI=,tag:cE3YHigXnj41vHHs2S+wkQ==,type:str]
          username: mghlaiel
          userID: 5adeaf66-29b5-40a8-ab88-a154659064a0
    clients:
        - id: kubermatic
          name: Kubermatic
          secret: ENC[AES256_GCM,data:Apd5cZUUGDBoaFhe/szjOP5vj/OHDpqZfIPmSB5fEtE=,iv:vNTD9I/76W4dhO4Ov1ly2+RTeHbT4tzjZ4PRLFKabnk=,tag:CJ5lodYhFF3cd2TMG1WF/Q==,type:str]
          RedirectURIs:
            - https://tn.creometry.com
            - https://tn.creometry.com/projects
        - id: kubermaticIssuer
          name: Kubermatic OIDC Issuer
          secret: ENC[AES256_GCM,data:0flWSQJs52+sAH0Kpd8JNg==,iv:LzdByGqprSlfLv9axkj8Gz3JCLpxFC3HkigcUfr1e3U=,tag:WEBJyLriiocWo4F+lNurqA==,type:str]
          RedirectURIs:
            - https://tn.creometry.com/api/v1/kubeconfig
        - id: prometheus
          name: Prometheus
          secret: ENC[AES256_GCM,data:4o3U7VU++RAJnNwAV6eV0w==,iv:ZMrT4xDeW97O+RW0HEjgZcuHg+gqJk1w571QNkRLb4A=,tag:bNGrGR9wVGbuM7DjfLCIsw==,type:str]
          RedirectURIs:
            - https://prometheus.tn.creometry.com/oauth/callback
        - id: alertmanager
          name: Alertmanager
          secret: ENC[AES256_GCM,data:kO/sKVpFLczMptN3o1woqg==,iv:NB9oQzUS9SQrZmg6pTnGq3nrF4VmqMjdDDtWV1c/Nso=,tag:8frzERowi8MeYRL3zC8JdA==,type:str]
          RedirectURIs:
            - https://alertmanager.tn.creometry.com/oauth/callback
        - id: grafana
          name: Grafana
          secret: ENC[AES256_GCM,data:ONRQjQ7pKQ+PwJKfBU1W/g==,iv:WMNVCTRgeqO/Wh3NnjinSRTOSq2phwEUTnQX1gXn7oE=,tag:hqW2+sVnDKg2iQkWvAghAg==,type:str]
          RedirectURIs:
            - https://grafana.tn.creometry.com/oauth/callback
        - id: karma
          name: Karma
          secret: ENC[AES256_GCM,data:oCqdVUfMymusJasFQVxw6w==,iv:Rsc4pLWaT3uU1fiUOmzjm/SQlVRk2LmQ98zY+kBqWHc=,tag:qaSzIab1wp2PRtExbCTIag==,type:str]
          RedirectURIs:
            - https://karma.tn.creometry.com/oauth/callback
alertmanager:
    host: alertmanager.tn.creometry.com
grafana:
    user: admin
    password: ENC[AES256_GCM,data:pm5tXiIb1s+p7H0ZpevM0Q==,iv:1rga1gmt7Cs/22FXbzZnctA0B0N2pF5vZFBH4Qu2zZs=,tag:UK3cTOuFYwiQrVfFlsx6mw==,type:str]
    provisioning:
        configuration:
            auto_assign_org_role: Editor
            disable_login_form: false
            root_url: https://grafana.tn.creometry.com
        datasources:
            lokiServices:
                - loki
prometheus:
    host: prometheus.tn.creometry.com
    storageSize: 125Gi
    tsdb:
        retentionTime: 7d
    ruleFiles:
        - /etc/prometheus/rules/general-*.yaml
        - /etc/prometheus/rules/kubermatic-*.yaml
        - /etc/prometheus/rules/managed-*.yaml
iap:
    oidc_issuer_url: https://tn.creometry.com/dex
    deployments:
        prometheus:
            name: prometheus
            ingress:
                host: prometheus.tn.creometry.com
            upstream_service: prometheus.monitoring.svc.cluster.local
            upstream_port: 9090
            client_id: prometheus
            client_secret: ENC[AES256_GCM,data:+JCkTvVNVLRKBNjH/y9ZUg==,iv:k2bgSIYgsKGN0aE4W7NMXxRbO3iKRGpA3GQ/yl36bM0=,tag:bjq9N7nXEFn0l2Hq+XI9OQ==,type:str]
            encryption_key: ENC[AES256_GCM,data:WsMOff/lth4z6cAdMCCVYhYcjHzQJa0O5AYmYHkND9g=,iv:5VW4wzGhOIXhY6azXmoDGMS1b2LqP46KmO7c9ehwTYI=,tag:9iCHATSul07hDpmaDMTI9w==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - ""
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        alertmanager:
            name: alertmanager
            ingress:
                host: alertmanager.tn.creometry.com
            upstream_service: alertmanager.monitoring.svc.cluster.local
            upstream_port: 9093
            client_id: alertmanager
            client_secret: ENC[AES256_GCM,data:/0Z0WCjCY7OnE+hCEQf1Kw==,iv:etDVI6FFbVFZeHJLKRniQFVFlJGon5pIHhZLIHC7ohY=,tag:+m1P4CFjJZJIyB9lrZTa1A==,type:str]
            encryption_key: ENC[AES256_GCM,data:+QAjDSRqf+PyWWZ1tkYZXGUJtj22vrKZS9AqzCIomVY=,iv:SC+IQHldbC1cZ+sonGc2hXJ4uppu4IBEMQKzavyxQQM=,tag:oRhpETTYFwXWMttpO8RT3A==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - ""
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        grafana:
            name: grafana
            ingress:
                host: grafana.tn.creometry.com
            upstream_service: grafana.monitoring.svc.cluster.local
            upstream_port: 3000
            client_id: grafana
            client_secret: ENC[AES256_GCM,data:2O1371SDc0Z0VWa0ot6HOQ==,iv:LfPJOwLUDO+IiASiv7vndCyz+qI2oZblaQkBbBjZRuE=,tag:CCEdy5jrpPrldc+J/fDG/g==,type:str]
            encryption_key: ENC[AES256_GCM,data:Z+L/YURDGboxuxvgfwS4blTDlIoF+v/3bjpx9nfJy4E=,iv:5YeUn+R7g8QV5yCbLBRfW70ezmIthMpT8pBdnib9YmU=,tag:6I31M56H703A6bvtfh6aCg==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - ""
                pass_user_headers: true
                skip_auth_regex:
                    - /api/health
        karma:
            name: karma
            ingress:
                host: karma.tn.creometry.com
            upstream_service: karma.monitoring.svc.cluster.local
            upstream_port: 8080
            client_id: karma
            client_secret: ENC[AES256_GCM,data:bXjpYPr/uNPxWFkzT7rBRw==,iv:5CaH6BNh/uE+2tNtklGYhNGw3vvcbAOdUHksE+ecsrU=,tag:IIXVl7mtwyNJA9uUH1Xf6Q==,type:str]
            encryption_key: ENC[AES256_GCM,data:W6zh6ne8CpEPQ9pIbzBrShk7OG19yhFbIwXWAPCZ07Q=,iv:70uH+m52sp3P3FYN2McPjiMeQCDfr0cB09Ef0OTyZts=,tag:QwXMOyb/KcoizxEOC2W0KQ==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - ""
                pass_user_headers: true
telemetry:
    # uuid is the unique identifier of the client where the agent is running.
    # This field is required and will print an error message when that entry is missing.
    uuid: 9c0cf52b-0229-42b6-8449-a2607ee15180
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wuun9qgc25l3ps6sy6298er9d5aud9d5jz9gmj3sjx3trwxwsplqxv75qc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabFdodGJJVGhPaEozSnpH
            ZDNDSDdVaThjRlpndFdZOVFYaytybEE2QzFvCjFCK0grNFY4SDdGLzFoWHlXSkFt
            TWhHeGFEd3h5TGVobTJPWmpFR0RYNTQKLS0tIGhpYWd1ekpGelhkbmRLZk4zSCta
            UVd4UzVpZUloU0VpRFpxUjUyY2dMQjgKQT3wgUnVqVkJSbEJMysB9MEbLpqWEn4z
            gPvF/xl96CC9pJnQ1C3FPmVgZrcuwQmuzhDl3ebgTrES5cj6sk7z/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-03T17:43:14Z"
    mac: ENC[AES256_GCM,data:az+r4jKP7X5eOKRvST75zt0BMbhs6hIv9se2h/u5pQFST8mCO/WQp/WJTXFm/Nccqj8apmfGgw4naTysqFXh2rXI1A/Z3EzCt++KN9XY4a9xmURVJ4fcSzRmDZ981OggL8Bkf2FmUhaUxLg9JcipB6GZ51Qof1i8WIQMHWAE7Zg=,iv:wgDcnbTDy0SJAaBdncZkPmUjKCchl5KNp3A0v9sCSyE=,tag:eJHAz2t5bsfMh2fx662kOg==,type:str]
    pgp: []
    encrypted_regex: (hash|secret|password|encryption_key|accessKey)
    version: 3.7.1
