apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  country: Tunisia
  datacenters:
    TN-DC:
      country: "Tunisia"
      location: "TN"
      spec:
        gcp:
          region: "eu-west3"
          zone_suffixes:
            - a
            - b
            - c
  kubeconfig:
    name: kubeconfig-cluster
    namespace: kubermatic
